services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: "${PROJECT_NAME}-name-front"
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: "${PROJECT_NAME}-name-back"
    ports:
      - "3100:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PAYLOAD_SECRET=devsecret
      - MONGODB_URI=mongodb://mongo:27017/payload
    depends_on:
      - mongo
