services:
  # FRONT DU PROJET
  # -----------------------------------------------------------------
  front:
    image: kevinad/dreamsite-web-front  # Image de ton Next.js
    container_name: ${PROJECT_NAME}-front # Nom de l'image
    restart: always
    ports:
      - "3000:3000"  # Expose Next.js
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}  # URL de Strapi
      - NEXT_PUBLIC_API_TOKEN=${NEXT_PUBLIC_API_TOKEN}
    depends_on:
      - cms  # Démarre après Strapi
      - mysql
    networks:
      - ${PROJECT_NAME}-network

  # CONSOLE CMS
  # -----------------------------------------------------------------
  cms:
    image: kevinad/dreamsite-cms  # Image de ton Strapi
    container_name: ${PROJECT_NAME}-cms # Nom de l'image
    restart: always
    ports:
      - "1337:1337"  # Expose Strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - mysql  # Démarre après MySQL
    networks:
      - ${PROJECT_NAME}-network

  cms_db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-db # Nom de l'image
    restart: always
    ports:
      - "3306:3306"  # Expose MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql  # Persistance des données
    networks:
      - ${PROJECT_NAME}-network

volumes:
  mysql_data:

networks:
  ${PROJECT_NAME}-network: